class ServiceLists{
  static final List<String> _competitionsList = ['Online Courses','Competitions','Conferences','Internships','Fellowships','Grants','Workshops','Scholarships','Miscellaneous'];
  static final List<String> _fundingTypeList = ['None','Fully Funded','Partially Funded','Self Funded','Paid','Unpaid'];
  static final List<String> _countriesList = [
    "Global",
    "Multiple Region",
    "Online",
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    //"Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bonaire",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territor",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    //"Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos",
    "Colombia",
    "Comoros",
    "Congo",
    //"Congo",
    "Cook Islands",
    "Costa Rica",
    "Croatia",
    "Cuba",
    //"Curaçao",
    "Cyprus",
    "Czechia",
    "Côte d'Ivoire",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    //"Equatorial Guinea",
    "Eritrea",
    "Estonia",
    //"Eswatini",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    //"Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran ",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea",
    "Korea (the Republic of)",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    //"Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger (the)",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "North Korea",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    //"Palestine, State of",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    //"Republic of North Macedonia",
    "Romania",
    "Russian Federation",
    "Rwanda",
    //"Réunion",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan (the)",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan",
    "Tajikistan",
    "Tanzania, United Republic of",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United States Minor Outlying Islands",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Venezuela",
    "Viet Nam",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ];


  static final Map<String,String> _competitionsMap = {
    'Online Courses' : 'ONLINE_COURSES',
    'Competitions' : 'COMPETITIONS',
    'Conferences' : 'CONFERENCES',
    'Internships' : 'INTERNSHIP',
    'Fellowships' : 'FELLOWSHIPS',
    'Grants' : 'GRANTS',
    'Workshops' : 'WORKSHOPS',
    'Scholarships' : 'SCHOLARSHIPS',
    'Miscellaneous' : 'MISCELLANEOUS'
  };


  static final Map<String,String> _fundingMap = {
    'None' : 'NONE',
    'Fully Funded' : 'FullyFunded',
    'Partially Funded' : 'PartiallyFunded',
    'Self Funded' : 'SelfFunded',
    'Paid' : 'PAID',
    'Unpaid' : 'UNPAID'
  };

  static final Map<String,String> _countryMap = {
    "Any"  : "ANY",
    "Global" : "WW",
    "Multiple Region" : "DV",
    "Online" : "OL",
    "Afghanistan" : "AF",
    "Albania" : "AL",
    "Algeria" : "DZ",
    "American Samoa" : "AS",
    "Andorra" : "AD",
    "Angola" : "AO",
    "Anguilla" : "AI",
    "Antarctica" : "AQ",
    "Antigua and Barbuda" : "AG",
    "Argentina" : "AR",
    "Armenia" : "AM",
    "Aruba" : "AW",
    "Australia" : "AU",
    "Austria" : "AT",
    "Azerbaijan" : "AZ",
    //"Bahamas" : "",
    "Bahrain" : "BH",
    "Bangladesh" : "BD",
    "Barbados" : "BB",
    "Belarus" : "BY",
    "Belgium" : "BE",
    "Belize" : "BZ",
    "Benin" : "BJ",
    "Bermuda" : "BM",
    "Bhutan" : "BT",
    "Bolivia" : "BO",
    "Bonaire" : "BQ",
    "Bosnia and Herzegovina" : "BA",
    "Botswana" : "BW",
    "Bouvet Island" : "BV",
    "Brazil" : "BR",
    "British Indian Ocean Territor" : "BO",
    "Brunei Darussalam" : "BN",
    "Bulgaria" : "BG",
    "Burkina Faso" : "BF",
    "Burundi" : "BU",
    //"Cabo Verde" : "",
    "Cambodia" : "KH",
    "Cameroon" : "CM",
    "Canada" : "CA",
    "Cayman Islands" : "KY",
    "Central African Republic" : "CF",
    "Chad" : "TD",
    "Chile" : "CL",
    "China" : "CN",
    "Christmas Island" : "CX",
    "Cocos" : "CC",
    "Colombia" : "CO",
    "Comoros" : "KM",
    "Congo" : "CG",
    //"Congo" : "",
    "Cook Islands" : "CK",
    "Costa Rica" : "CR",
    "Croatia" : "HR",
    "Cuba" : "CU",
    //"Curaçao" : "",
    "Cyprus" : "CY",
    "Czech Republic" : "CZ",
    "Côte d'Ivoire" : "",
    "Denmark" : "DK",
    "Djibouti" : "DJ",
    "Dominica" : "DM",
    "Dominican Republic" : "DO",
    "Ecuador" : "EC",
    "Egypt" : "EG",
    "El Salvador" : "SV",
    //"Equatorial Guinea" : "",
    "Eritrea" : "ER",
    "Estonia" : "EE",
    //"Eswatini" : "",
    "Ethiopia" : "ET",
    "Falkland Islands" : "FK",
    "Faroe Islands" : "FO",
    "Fiji" : "FJ",
    "Finland" : "FI",
    "France" : "FR",
    "French Guiana" : "GF",
    "French Polynesia" : "PF",
    "French Southern Territories" : "TF",
    "Gabon" : "GA",
    "Gambia" : "GM",
    "Georgia" : "GE",
    "Germany" : "DE",
    "Ghana" : "GH",
    "Gibraltar" : "GI",
    "Greece" : "GR",
    "Greenland" : "GL",
    "Grenada" : "GD",
    "Guadeloupe" : "GP",
    "Guam" : "GU",
    "Guatemala" : "GT",
    //"Guernsey" : "",
    "Guinea" : "GN",
    "Guinea-Bissau" : "GW",
    "Guyana" : "GY",
    "Haiti" : "HT",
    "Holy See" : "VA",
    "Honduras" : "HN",
    "Hong Kong" : "HK",
    "Hungary" : "HU",
    "Iceland" : "IS",
    "India" : "IN",
    "Indonesia" : "ID",
    "Iran " : "IR",
    "Iraq" : "IQ",
    "Ireland" : "IE",
    "Isle of Man" : "IM",
    "Israel" : "IE",
    "Italy" : "IT",
    "Jamaica" : "JM",
    "Japan" : "JP",
    "Jersey" : "JE",
    "Jordan" : "JO",
    "Kazakhstan" : "KZ",
    "Kenya" : "KE",
    "Kiribati" : "KI",
    "Kuwait" : "KW",
    "Kyrgyzstan" : "KG",
    "Lao People's Democratic Republic" : "LA",
    "Latvia" : "LV",
    "Lebanon" : "LB",
    "Lesotho" : "LS",
    "Liberia" : "LR",
    "Libya" : "LY",
    "Liechtenstein" : "LI",
    "Lithuania" : "LT",
    "Luxembourg" : "LU",
    "Macao" : "MO",
    "Madagascar" : "MG",
    "Malawi" : "MW",
    "Malaysia" : "MY",
    "Maldives" : "MV",
    "Mali" : "ML",
    "Malta" : "MT",
    "Marshall Islands" : "MH",
    "Martinique" : "MQ",
    "Mauritania" : "MQ",
    "Mauritius" : "MU",
    "Mayotte" : "YT",
    "Mexico" : "MX",
    //"Micronesia" : "",
    "Moldova" : "MD",
    "Monaco" : "MC",
    "Mongolia" : "MN",
    "Montenegro" : "ME",
    "Montserrat" : "MS",
    "Morocco" : "MA",
    "Mozambique" : "MZ",
    "Myanmar" : "MM",
    "Namibia" : "NA",
    "Nauru" : "NR",
    "Nepal" : "NP",
    "Netherlands" : "NL",
    "Netherlands Antilles" : "AN",
    "New Caledonia" : "NC",
    "New Zealand" : "NZ",
    "Nicaragua" : "NI",
    "Niger (the)" : "NE",
    "Nigeria" : "NG",
    "Niue" : "NU",
    "Norfolk Island" : "NF",
    "North Korea" : "KP",
    "Northern Mariana Islands" : "MP",
    "Norway" : "NO",
    "Oman" : "OM",
    "Pakistan" : "PK",
    "Palau" : "PW",
    //"Palestine, State of" : "",
    "Panama" : "PA",
    "Papua New Guinea" : "PG",
    "Paraguay" : "PY",
    "Peru" : "PE",
    "Philippines" : "PH",
    "Pitcairn" : "PN",
    "Poland" : "PL",
    "Portugal" : "PT",
    "Puerto Rico" : "PR",
    "Qatar" : "QA",
    //"Republic of North Macedonia" : "",
    "Romania" : "RO",
    "Russian Federation" : "RU",
    "Rwanda" : "RW",
    //"Réunion" : "",
    "Samoa" : "WS",
    "San Marino" : "SM",
    "Sao Tome and Principe" : "ST",
    "Saudi Arabia" : "SA",
    "Senegal" : "SN",
    "Serbia" : "RS",
    "Seychelles" : "SC",
    "Sierra Leone" : "SL",
    "Singapore" : "SG",
    "Sint Maarten" : "SX",
    "Slovakia" : "SK",
    "Slovenia" : "SI",
    "Solomon Islands" : "SB",
    "Somalia" : "SO",
    "South Africa" : "ZA",
    "South Georgia and the South Sandwich Islands" : "GS",
    "South Korea" : "KR",
    "South Sudan" : "SS",
    "Spain" : "ES",
    "Sri Lanka" : "LK",
    "Sudan (the)" : "SD",
    "Suriname" : "SR",
    "Svalbard and Jan Mayen" : "SJ",
    "Sweden" : "SE",
    "Switzerland" : "CH",
    "Syrian Arab Republic" : "SY",
    "Taiwan" : "TW",
    "Tajikistan" : "TJ",
    "Tanzania, United Republic of" : "TZ",
    "Thailand" : "TH",
    "Timor-Leste" : "TL",
    "Togo" : "TG",
    "Tokelau" : "TK",
    "Tonga" : "TO",
    "Trinidad and Tobago" : "TT",
    "Tunisia" : "TN",
    "Turkey" : "TR",
    "Turkmenistan" : "TM",
    "Turks and Caicos Islands" : "TC",
    "Tuvalu" : "TV",
    "Uganda" : "UG",
    "Ukraine" : "UA",
    "United Arab Emirates" : "AE",
    "United Kingdom" : "GB",
    "United States Minor Outlying Islands" : "UM",
    "United States of America" : "US",
    "Uruguay" : "UY",
    "Uzbekistan" : "UZ",
    //"Vanuatu" : "",
    "Venezuela" : "VE",
    "Viet Nam" : "VN",
    "Wallis and Futuna" : "WF",
    "Western Sahara" : "EH",
    "Yemen" : "YE",
    "Zambia" : "ZM",
    "Zimbabwe" : "ZW",
    //"Åland Islands" : ""
  };

  static List<String> get competitionsList => _competitionsList;
  static List<String> get fundingTypeList => _fundingTypeList;
  static List<String> get countriesList => _countriesList;
  static Map<String,String> get fundingMap => _fundingMap;
  static Map<String,String> get competitionsMap => _competitionsMap;
  static Map<String,String> get countryMap => _countryMap;
}